### ISSUE TITLE
Stuck in version 1.1

### ISSUE THREAD

**Issue by shiu129** [DoranekoSystems/ceserver-ios#10]
I can see the process list. After selecting an app and attaching, it gets stuck at "CMD_GETARCHITECTURE (1)=3". This issue occurs only in version 1.1, while version 1.0 works fine

**Comment by DoranekoSystems** [comment]
Thanks for the report.
What is the version of your cheat engine itself?

**Comment by shiu129** [comment]
Using version 7.5.
 I forgot to mention, I am using an iPhone12 iOS16.1.2 rootless (Dopamine).

**Comment by DoranekoSystems** [comment]
Fixed in latest commit.
Please set the appropriate ceversion in config.ini.
https://github.com/DoranekoSystems/ceserver-ios/actions/runs/12258878771
